[versions]
compileSdk = "37"
targetSdk = "37"
minSdk = "24"
accompanistPermissions = "0.37.3"
agp = "9.2.1"
nav3Core = "1.1.1"
coilCompose = "3.4.0"
coilNetworkOkhttp = "3.4.0"
composeBomVersion = "2026.05.00"
kotlin = "2.3.21"
material3 = "1.5.0-alpha19"
materialIconsCore = "1.7.8"
ui = "1.11.1"
kotlinSerialization = "2.3.21"
kotlinxSerializationCore = "1.11.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization"}